# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bpv3aNCosKBRDs6Oc7ldQdLV44fFUu7PHbA2xsVO/GOUryG7JljLz0gAuOxTB5/cRCYZ8K1OU2kyfbfqlYCko0r1VwECJ/8xh9YTFMWoXWK/vmSexdwrshjzxGwQKYODpXvI0MuCWUtQf93grU2gQ/Mw4xL9cxMi78yNpH0fMwFSi/wPO2LKLVLlBsWu193ofP5ooEoAUm2RCUFXvMvcAkMr1YjFCctDFN8Or+k9px4qBFjKTXCcQXYfoovQ7lfPX8sIVSA+mfzxUL8hxZ8sq3Dax1ADJfNdwfX44n6un231AFixP370/4mjLdej/kGrbu67XLJBvtupKglb7E5C9S4HXKtxMdSeNCYRqe6r+1fk+stSTnZ541xBfrReBrHzadbb6pGOXASMcA9X6LyBito2knOhAcZpG8l+F0rdvm1jvlfamZKL0paQZJohdu5/au7a6w8mO1+A4HS4PpFz5G1bHtm6XRYdgPm3qvtb4WYjjb+lAx08ghrIAVsJqxJFO/h+9HfxoMrDEL1Avaoy8CoBbDntqVRv+DZMPbOTTPMSzTxaT7LfyR4o5AXE10ANmWgwVxJN64Vi1ReVn31m9PKiTq4P4NJXuEwtp/yHRsIQHftzifq4qTgW6IiOfVGdHO5qKRpK4tFDnUNxB69S7uWO7rcAaxPHRA08ueJUndE="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
