travis:
  secure:
    BINSTAR_TOKEN: bpv3aNCosKBRDs6Oc7ldQdLV44fFUu7PHbA2xsVO/GOUryG7JljLz0gAuOxTB5/cRCYZ8K1OU2kyfbfqlYCko0r1VwECJ/8xh9YTFMWoXWK/vmSexdwrshjzxGwQKYODpXvI0MuCWUtQf93grU2gQ/Mw4xL9cxMi78yNpH0fMwFSi/wPO2LKLVLlBsWu193ofP5ooEoAUm2RCUFXvMvcAkMr1YjFCctDFN8Or+k9px4qBFjKTXCcQXYfoovQ7lfPX8sIVSA+mfzxUL8hxZ8sq3Dax1ADJfNdwfX44n6un231AFixP370/4mjLdej/kGrbu67XLJBvtupKglb7E5C9S4HXKtxMdSeNCYRqe6r+1fk+stSTnZ541xBfrReBrHzadbb6pGOXASMcA9X6LyBito2knOhAcZpG8l+F0rdvm1jvlfamZKL0paQZJohdu5/au7a6w8mO1+A4HS4PpFz5G1bHtm6XRYdgPm3qvtb4WYjjb+lAx08ghrIAVsJqxJFO/h+9HfxoMrDEL1Avaoy8CoBbDntqVRv+DZMPbOTTPMSzTxaT7LfyR4o5AXE10ANmWgwVxJN64Vi1ReVn31m9PKiTq4P4NJXuEwtp/yHRsIQHftzifq4qTgW6IiOfVGdHO5qKRpK4tFDnUNxB69S7uWO7rcAaxPHRA08ueJUndE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
